### PR TITLE
fix: add lock for concurrent map access

### LINKED ISSUE #72: Concurrency issue in enforcer.go
1. We are load testing the server using k6 tool and when i try to load the server with multiple users it crashes.
2. The issue is that the maps used in enforcer.go (enforcerMap and adapterMap) need to be thread safe.
3. Use either a sync map OR a RWMutex and protect the code where map is being written into.
4. I was able to resolve it for myself using mutex, urge you to do the same.

### PR DESCRIPTION
**Pull request by JalinWang**
fix: https://github.com/casbin/casbin-server/issues/72

### CODE REVIEW

File: server/enforcer.go [hunk 1]
```diff
@@ -30,6 +31,7 @@ import (
 type Server struct {
 	enforcerMap map[int]*casbin.Enforcer
 	adapterMap  map[int]persist.Adapter
+	mu          sync.RWMutex
```
Comment (nsarup) [inline server/enforcer.go]: Just one comment- as there are 2 maps better to use 2 mutexes (else there will be a scenario where you will be blocking write to one map when writing to the other map).

**Review by nsarup — CHANGES_REQUESTED** [review]

File: server/enforcer.go (hunk 1 above)
Comment (JalinWang) [reply server/enforcer.go]: 😰you are right. My baaaad

**Review by nsarup — APPROVED** [review]
